{"name": "Проверка ошибки авторизации несуществующего курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'LIYcZg', 'password': 'kaLmNX'}"}, {"name": "status_code", "value": "404"}, {"name": "response_text", "value": "{'code': 404, 'message': 'Учетная запись не найдена'}"}], "start": 1736670166579, "stop": 1736670166812, "uuid": "263f4f28-74b5-41a2-ae63-30e97f8ba366", "historyId": "3db87fffc4f48e139866b8065b2d2944", "testCaseId": "7391b43a477e729412655a4faee92fb0", "fullName": "tests.test_login_courier.TestLoginCourier#test_not_exists_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "36228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}